import type { Metadata } from "next";
import { notFound } from "next/navigation";
import ProductPage, { type ProductPageProps } from "@/components/ProductPage";

const CATEGORIES = [
  "development-it",
  "design-creative",
  "writing-content",
  "sales-marketing",
  "finance-operations",
  "engineering",
  "customer-support",
  "consulting",
];

const PAGES: Record<string, ProductPageProps> = {
  "find-work": {
    eyebrow: "For freelancers and job seekers",
    title: "Find work that fits before you apply.",
    description: "Sckoll watches the market for projects, contracts, and roles that match your skills, experience, and direction—then helps you make a stronger move.",
    primaryLabel: "Create your work profile",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "Browse opportunity types",
    secondaryHref: "/categories/development-it",
    tone: "dark",
    stats: [{ value: "24/7", label: "opportunity radar" }, { value: "0.82+", label: "fit threshold" }, { value: "1", label: "profile to manage it all" }],
    cards: [
      { label: "DISCOVER", title: "Recommended opportunities", description: "A feed shaped around your actual work, not generic keywords.", href: "/recommended" },
      { label: "APPLY", title: "AI proposal assistant", description: "Turn your context into a concise, relevant application or pitch.", href: "/proposal-assistant" },
      { label: "TRACK", title: "Your opportunity pipeline", description: "Keep matched, pitched, interviewing, and closed work in one place.", href: "/pipeline" },
    ],
    steps: [
      { number: "01", title: "Build your profile", description: "Add skills, proof of work, experience, and what you want next." },
      { number: "02", title: "Review your matches", description: "See why an opportunity fits before you spend time applying." },
      { number: "03", title: "Send with context", description: "Approve a tailored pitch, then track what happens next." },
    ],
  },
  "find-talent": {
    eyebrow: "For founders, agencies, and lean teams",
    title: "Find the right person without becoming a recruiter.",
    description: "Describe the outcome you need, discover high-intent talent, and move from shortlist to signed contract in one focused hiring room.",
    primaryLabel: "Start finding talent",
    primaryHref: "/sign-up?role=client",
    secondaryLabel: "See how matching works",
    secondaryHref: "/matching-engine",
    tone: "acid",
    stats: [{ value: "1", label: "focused hiring room" }, { value: "3x", label: "less manual screening" }, { value: "100%", label: "human-approved decisions" }],
    cards: [
      { label: "SOURCE", title: "Search by outcome", description: "Start with the work you need done, not a stack of empty filters.", href: "/talent-search" },
      { label: "COMPARE", title: "Shortlist with your team", description: "Share notes, compare proof, and keep hiring decisions in context.", href: "/team-workspace" },
      { label: "START", title: "Move into a contract", description: "Agree on scope, milestones, timing, and payment without losing the thread.", href: "/contracts" },
    ],
    steps: [
      { number: "01", title: "Describe the outcome", description: "Tell Sckoll what success looks like and which skills matter." },
      { number: "02", title: "Review the shortlist", description: "Compare people using proof, fit, availability, and intent." },
      { number: "03", title: "Start with confidence", description: "Set clear terms and move the right person into the work." },
    ],
  },
  "how-it-works": {
    eyebrow: "The Sckoll workflow",
    title: "A better path from opportunity to outcome.",
    description: "One marketplace for discovering work, finding people, making the pitch, agreeing on terms, and keeping momentum after the match.",
    primaryLabel: "Create your free profile",
    primaryHref: "/sign-up",
    secondaryLabel: "Explore the trust layer",
    secondaryHref: "/trust",
    tone: "paper",
    features: [
      { label: "01 / DISCOVER", title: "Let the right signal come to you", description: "Your radar aggregates opportunities and demand across the places you would otherwise search manually." },
      { label: "02 / MATCH", title: "Rank fit by more than keywords", description: "Skills, proof, seniority, intent, and context combine into a match you can understand." },
      { label: "03 / MOVE", title: "Keep the human in control", description: "AI drafts the next action. You decide what gets sent, signed, and started." },
    ],
    steps: [
      { number: "01", title: "Create your signal", description: "Tell Sckoll what you can do, what you need, or who you want to hire." },
      { number: "02", title: "Discover the fit", description: "See relevant opportunities or people ranked by skills and proof." },
      { number: "03", title: "Make a stronger move", description: "Generate a focused application, pitch, shortlist, or project brief." },
      { number: "04", title: "Agree with confidence", description: "Keep terms, scope, milestones, and conversations together." },
    ],
  },
  "matching-engine": {
    eyebrow: "Why Sckoll",
    title: "Matching that understands the work behind the words.",
    description: "Sckoll combines semantic profile understanding with skills, seniority, proof, and intent so the feed gets more useful over time.",
    primaryLabel: "Build your match profile",
    primaryHref: "/sign-up",
    secondaryLabel: "Find work",
    secondaryHref: "/find-work",
    tone: "dark",
    features: [
      { label: "CONTEXT", title: "Understands the brief", description: "A project is more than a title. Sckoll reads the outcome, constraints, and signals behind it." },
      { label: "EVIDENCE", title: "Uses proof of work", description: "Profiles become stronger when experience, links, results, and skills work together." },
      { label: "CONTROL", title: "Explains the fit", description: "See the shared skills and reasons behind a recommendation before you act." },
    ],
  },
  "trust": {
    eyebrow: "Trust & safety",
    title: "Move quickly without stepping into the dark.",
    description: "Sckoll is designed for real people, real money, and the messy middle between a promising match and completed work.",
    primaryLabel: "Create a verified profile",
    primaryHref: "/sign-up",
    secondaryLabel: "Read the workflow",
    secondaryHref: "/how-it-works",
    tone: "paper",
    features: [
      { label: "IDENTITY", title: "Verified professional profiles", description: "Link your professional graph and build trust from real experience and proof." },
      { label: "SAFETY", title: "Scam detection built in", description: "High-risk language and off-platform leakage patterns are flagged before they become costly." },
      { label: "PAYMENTS", title: "Milestone-safe work", description: "Keep scope, approvals, payment events, and audit trails connected to the contract." },
    ],
  },
  "proposal-assistant": {
    eyebrow: "For talent",
    title: "Stop sending the same proposal everywhere.",
    description: "Sckoll turns your profile and the opportunity brief into a specific, human-sounding application you can review and send.",
    primaryLabel: "Try it with your profile",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "See the full workflow",
    secondaryHref: "/how-it-works",
    tone: "acid",
    features: [
      { label: "CONTEXT", title: "Starts from the brief", description: "The assistant identifies what the client or hiring team actually needs." },
      { label: "VOICE", title: "Keeps your point of view", description: "Use your work, language, and proof instead of a generic generated paragraph." },
      { label: "CONTROL", title: "You approve every send", description: "Sckoll accelerates the draft—not your judgment." },
    ],
  },
  "pipeline": {
    eyebrow: "For talent",
    title: "Know what is moving and what needs a nudge.",
    description: "Turn scattered applications, client conversations, and interviews into a simple opportunity pipeline.",
    primaryLabel: "Build your pipeline",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "Find work",
    secondaryHref: "/find-work",
    tone: "paper",
    cards: [
      { label: "MATCHED", title: "New fit found", description: "Review the why before deciding whether to make a move." },
      { label: "PITCHED", title: "Follow up with intent", description: "See every open conversation and the next useful action." },
      { label: "CLOSED", title: "Build your proof", description: "Turn completed work into a stronger professional graph." },
    ],
  },
  "talent-search": {
    eyebrow: "For teams",
    title: "Search talent by the outcome you need.",
    description: "Use structured context, fit signals, and proof of work to move from a broad search to a shortlist you can trust.",
    primaryLabel: "Start a talent search",
    primaryHref: "/sign-up?role=client",
    secondaryLabel: "See team workspace",
    secondaryHref: "/team-workspace",
    tone: "dark",
    features: [
      { label: "SEARCH", title: "Start with the work", description: "Describe the project, role, or outcome before filtering down to a person." },
      { label: "FIT", title: "See relevant evidence", description: "Review shared skills, project proof, seniority, and intent in one view." },
      { label: "DECIDE", title: "Shortlist together", description: "Keep notes and decisions visible to the people involved in hiring." },
    ],
  },
  "team-workspace": {
    eyebrow: "For teams",
    title: "A hiring room, not another spreadsheet.",
    description: "Bring the brief, shortlist, notes, conversations, and next step into one place your team can actually use.",
    primaryLabel: "Create a team workspace",
    primaryHref: "/sign-up?role=client",
    secondaryLabel: "Find talent",
    secondaryHref: "/find-talent",
    tone: "acid",
    steps: [
      { number: "01", title: "Share the brief", description: "Keep the outcome and constraints visible from the start." },
      { number: "02", title: "Compare the shortlist", description: "Review proof and fit together, not in disconnected messages." },
      { number: "03", title: "Choose the next step", description: "Invite, interview, or contract with a clear decision trail." },
    ],
  },
  "contracts": {
    eyebrow: "Work agreements",
    title: "Make the terms as clear as the opportunity.",
    description: "Move from a good match to a good working relationship with scope, milestones, approvals, and payments connected from day one.",
    primaryLabel: "Start a secure agreement",
    primaryHref: "/sign-up",
    secondaryLabel: "Explore trust & safety",
    secondaryHref: "/trust",
    tone: "paper",
    features: [
      { label: "SCOPE", title: "Define what done means", description: "Translate a conversation into outcomes, timing, and responsibilities." },
      { label: "MILESTONES", title: "Keep progress visible", description: "Use approvals and delivery checkpoints to reduce uncertainty." },
      { label: "PAYMENT", title: "Protect the working relationship", description: "Keep payment events tied to the work and the agreed terms." },
    ],
  },
  "recommended": {
    eyebrow: "Your opportunity feed",
    title: "Recommendations that improve as you do.",
    description: "Sckoll learns from your profile, your choices, and the kind of work you want next—so discovery gets less noisy over time.",
    primaryLabel: "Personalize your feed",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "Browse all work",
    secondaryHref: "/find-work",
    tone: "dark",
  },
  "pricing": {
    eyebrow: "Simple by design",
    title: "Start free. Pay when Sckoll moves work forward.",
    description: "Create your profile and explore the marketplace without a subscription trap. Upgrade when you need more automation, collaboration, or volume.",
    primaryLabel: "Sign up free",
    primaryHref: "/sign-up",
    secondaryLabel: "Talk to the team",
    secondaryHref: "/contact",
    tone: "acid",
    stats: [{ value: "$0", label: "to create a profile" }, { value: "1", label: "workspace for both sides" }, { value: "0", label: "black-box commitments" }],
    features: [
      { label: "FREE", title: "Start with your profile", description: "Set up your signal, explore opportunities, and understand how the marketplace works." },
      { label: "PRO", title: "Move with more leverage", description: "Unlock deeper automation, more proposal support, and richer workflow tools." },
      { label: "TEAMS", title: "Scale your hiring motion", description: "Give lean teams the shared context they need to find and move with talent." },
    ],
  },
  "contact": {
    eyebrow: "Talk to Sckoll",
    title: "Tell us what you are trying to move.",
    description: "Whether you are looking for your next role, your next client, or the person who can help your team ship, we want to hear the context.",
    primaryLabel: "Create your profile",
    primaryHref: "/sign-up",
    secondaryLabel: "Read how it works",
    secondaryHref: "/how-it-works",
    tone: "paper",
    cards: [
      { label: "TALENT", title: "I am looking for work", description: "Find opportunities that fit your skills and direction.", href: "/find-work" },
      { label: "TEAM", title: "I need to find someone", description: "Source reliable talent without adding a recruiter.", href: "/find-talent" },
      { label: "PARTNER", title: "I want to work with Sckoll", description: "Share an idea, partnership, or question.", href: "/sign-up" },
    ],
  },
  "about": {
    eyebrow: "The Sckoll premise",
    title: "Good work should find the people ready to do it.",
    description: "Sckoll is building a more useful work marketplace—one that respects the time of the people looking for opportunity and the teams trying to find them.",
    primaryLabel: "Join Sckoll",
    primaryHref: "/sign-up",
    secondaryLabel: "See the engine",
    secondaryHref: "/how-it-works",
    tone: "dark",
    features: [
      { label: "THE PROBLEM", title: "Too much work is still manual", description: "People scroll, copy, paste, fill forms, chase replies, and manage work across disconnected tools." },
      { label: "THE IDEA", title: "Let intelligence handle the repetition", description: "Sckoll uses context and automation to make discovery and execution more focused." },
      { label: "THE STANDARD", title: "Keep people in control", description: "The system can recommend and draft. People still decide what happens next." },
    ],
  },
  "privacy": {
    eyebrow: "Sckoll policies",
    title: "Privacy that respects the work behind your profile.",
    description: "This page will contain the complete Sckoll privacy notice as the product moves into production. For now, we are explicit about what the platform is designed to protect: your identity, work history, conversations, and payment context.",
    primaryLabel: "Return home",
    primaryHref: "/",
    secondaryLabel: "Contact Sckoll",
    secondaryHref: "/contact",
    tone: "paper",
  },
  "terms": {
    eyebrow: "Sckoll policies",
    title: "Clear terms for a two-sided marketplace.",
    description: "This page will contain the complete Sckoll terms and conditions before production launch. The platform is designed around clear scope, human-approved actions, safe conversations, and accountable payment flows.",
    primaryLabel: "Return home",
    primaryHref: "/",
    secondaryLabel: "Contact Sckoll",
    secondaryHref: "/contact",
    tone: "paper",
  },
  "status": {
    eyebrow: "Platform status",
    title: "The Sckoll radar is being built in the open.",
    description: "Public status reporting will live here as the ingestion, matching, messaging, and payment systems come online.",
    primaryLabel: "Return home",
    primaryHref: "/",
    secondaryLabel: "How it works",
    secondaryHref: "/how-it-works",
    tone: "dark",
    stats: [{ value: "ONLINE", label: "landing experience" }, { value: "NEXT", label: "marketplace engine" }, { value: "SOON", label: "live status telemetry" }],
  },
  "profile": {
    eyebrow: "Your professional signal",
    title: "Build a profile that carries your proof.",
    description: "Bring your skills, experience, links, outcomes, and direction into one profile that can be matched to better work.",
    primaryLabel: "Create your profile",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "Find work",
    secondaryHref: "/find-work",
    tone: "paper",
    features: [
      { label: "IDENTITY", title: "Show what you actually do", description: "Use a clear headline, skills, and point of view—not a profile that says everything and nothing." },
      { label: "PROOF", title: "Connect the work", description: "Add projects, outcomes, links, and experience that make the fit easier to understand." },
      { label: "DIRECTION", title: "Tell Sckoll what is next", description: "Your goals and preferences help the radar find work that makes sense for you." },
    ],
  },
  "saved-searches": {
    eyebrow: "For talent",
    title: "Keep the searches worth returning to.",
    description: "Save the roles, skills, and project patterns you care about so Sckoll can help you notice the right opportunities sooner.",
    primaryLabel: "Save your first search",
    primaryHref: "/sign-up?role=talent",
    secondaryLabel: "Browse work",
    secondaryHref: "/find-work",
    tone: "dark",
    cards: [
      { label: "ROLE", title: "Senior product engineer", description: "Remote · full-time · product teams" },
      { label: "PROJECT", title: "React Native builds", description: "Fixed price · startup clients" },
      { label: "SKILL", title: "Technical writing", description: "Docs · developer tools · AI" },
    ],
  },
  "post-project": {
    eyebrow: "For clients and founders",
    title: "Post the outcome—not a vague job description.",
    description: "Give talented people enough context to decide if they can help, then let Sckoll find the strongest fit for the work.",
    primaryLabel: "Describe your project",
    primaryHref: "/sign-up?role=client",
    secondaryLabel: "Find talent first",
    secondaryHref: "/find-talent",
    tone: "acid",
    steps: [
      { number: "01", title: "Name the outcome", description: "Explain what needs to be true when the work is done." },
      { number: "02", title: "Add the context", description: "Share constraints, timing, skills, and the proof that matters." },
      { number: "03", title: "Review the fit", description: "Compare responses and move the right person into a clear agreement." },
    ],
  },
  "agencies": {
    eyebrow: "For agencies and solopreneurs",
    title: "Scale outreach without losing your voice.",
    description: "Aggregate leads, keep your client pipeline organized, and use context-aware drafts to turn more conversations into work.",
    primaryLabel: "Build an agency workspace",
    primaryHref: "/sign-up?role=client",
    secondaryLabel: "See the proposal assistant",
    secondaryHref: "/proposal-assistant",
    tone: "dark",
    features: [
      { label: "AGGREGATE", title: "Bring leads into one radar", description: "Stop checking every board, inbox, and referral channel separately." },
      { label: "PERSONALIZE", title: "Pitch from context", description: "Generate focused outreach that starts from the prospect and the work." },
      { label: "SCALE", title: "Keep every opportunity moving", description: "Track follow-ups, next actions, and active client conversations in one pipeline." },
    ],
  },
  "resources": {
    eyebrow: "Sckoll resources",
    title: "Practical guidance for moving work forward.",
    description: "Guides, playbooks, and product notes for finding work, hiring talent, writing better proposals, and building trust.",
    primaryLabel: "Start with how it works",
    primaryHref: "/how-it-works",
    secondaryLabel: "Contact Sckoll",
    secondaryHref: "/contact",
    tone: "paper",
    cards: [
      { label: "GUIDE", title: "Write a brief people can act on", description: "Make the outcome, context, and constraints clear.", href: "/post-project" },
      { label: "PLAYBOOK", title: "Build a profile with proof", description: "Turn scattered experience into a strong signal.", href: "/profile" },
      { label: "NOTE", title: "Why fit beats volume", description: "Better matching reduces wasted effort on both sides.", href: "/matching-engine" },
    ],
  },
  "success-stories": {
    eyebrow: "Proof in progress",
    title: "Better matches create better work stories.",
    description: "Sckoll success stories will follow the people and teams who use the platform to replace repetitive searching with useful momentum.",
    primaryLabel: "Become an early story",
    primaryHref: "/sign-up",
    secondaryLabel: "Talk to the team",
    secondaryHref: "/contact",
    tone: "dark",
    features: [
      { label: "TALENT", title: "From applications to conversations", description: "Show how a stronger match changes the quality of the first interaction." },
      { label: "TEAMS", title: "From brief to trusted shortlist", description: "Show how lean teams hire without adding layers of process." },
      { label: "WORK", title: "From signed scope to outcome", description: "Show the full thread, not just the moment someone was hired." },
    ],
  },
};

export function generateStaticParams() {
  return Object.keys(PAGES).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const page = PAGES[slug];
  return page ? { title: `${page.title} — Sckoll`, description: page.description } : { title: "Sckoll" };
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (CATEGORIES.includes(slug)) {
    const name = slug.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" & ");
    return <ProductPage eyebrow="Browse Sckoll" title={`${name} work and talent.`} description={`Explore ${name.toLowerCase()} opportunities, skills, and people matched around the work that needs to get done.`} primaryLabel="Explore this category" primaryHref="/sign-up" secondaryLabel="Search all work" secondaryHref="/find-work" tone="paper" stats={[{ value: "LIVE", label: "category discovery" }, { value: "FIT", label: "semantic matching" }, { value: "SAFE", label: "verified workflow" }]} features={[{ label: "DISCOVER", title: `Find ${name.toLowerCase()} opportunities`, description: "Search projects, contracts, and roles with context behind every result." }, { label: "MATCH", title: "Show your strongest proof", description: "Build a profile that connects your experience to the work you want next." }, { label: "MOVE", title: "Turn interest into action", description: "Draft a pitch, shortlist a person, or start a clear agreement." }]} />;
  }
  if (!PAGES[slug]) notFound();
  return <ProductPage {...PAGES[slug]} />;
}
